require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompletedExercisesController do

  # This should return the minimal set of attributes required to create a valid
  # CompletedExercise. As you add validations to CompletedExercise, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "exercise_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompletedExercisesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all completed_exercises as @completed_exercises" do
      completed_exercise = CompletedExercise.create! valid_attributes
      get :index, {}, valid_session
      assigns(:completed_exercises).should eq([completed_exercise])
    end
  end

  describe "GET show" do
    it "assigns the requested completed_exercise as @completed_exercise" do
      completed_exercise = CompletedExercise.create! valid_attributes
      get :show, {:id => completed_exercise.to_param}, valid_session
      assigns(:completed_exercise).should eq(completed_exercise)
    end
  end

  describe "GET new" do
    it "assigns a new completed_exercise as @completed_exercise" do
      get :new, {}, valid_session
      assigns(:completed_exercise).should be_a_new(CompletedExercise)
    end
  end

  describe "GET edit" do
    it "assigns the requested completed_exercise as @completed_exercise" do
      completed_exercise = CompletedExercise.create! valid_attributes
      get :edit, {:id => completed_exercise.to_param}, valid_session
      assigns(:completed_exercise).should eq(completed_exercise)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CompletedExercise" do
        expect {
          post :create, {:completed_exercise => valid_attributes}, valid_session
        }.to change(CompletedExercise, :count).by(1)
      end

      it "assigns a newly created completed_exercise as @completed_exercise" do
        post :create, {:completed_exercise => valid_attributes}, valid_session
        assigns(:completed_exercise).should be_a(CompletedExercise)
        assigns(:completed_exercise).should be_persisted
      end

      it "redirects to the created completed_exercise" do
        post :create, {:completed_exercise => valid_attributes}, valid_session
        response.should redirect_to(CompletedExercise.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved completed_exercise as @completed_exercise" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedExercise.any_instance.stub(:save).and_return(false)
        post :create, {:completed_exercise => { "exercise_id" => "invalid value" }}, valid_session
        assigns(:completed_exercise).should be_a_new(CompletedExercise)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedExercise.any_instance.stub(:save).and_return(false)
        post :create, {:completed_exercise => { "exercise_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested completed_exercise" do
        completed_exercise = CompletedExercise.create! valid_attributes
        # Assuming there are no other completed_exercises in the database, this
        # specifies that the CompletedExercise created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CompletedExercise.any_instance.should_receive(:update).with({ "exercise_id" => "1" })
        put :update, {:id => completed_exercise.to_param, :completed_exercise => { "exercise_id" => "1" }}, valid_session
      end

      it "assigns the requested completed_exercise as @completed_exercise" do
        completed_exercise = CompletedExercise.create! valid_attributes
        put :update, {:id => completed_exercise.to_param, :completed_exercise => valid_attributes}, valid_session
        assigns(:completed_exercise).should eq(completed_exercise)
      end

      it "redirects to the completed_exercise" do
        completed_exercise = CompletedExercise.create! valid_attributes
        put :update, {:id => completed_exercise.to_param, :completed_exercise => valid_attributes}, valid_session
        response.should redirect_to(completed_exercise)
      end
    end

    describe "with invalid params" do
      it "assigns the completed_exercise as @completed_exercise" do
        completed_exercise = CompletedExercise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedExercise.any_instance.stub(:save).and_return(false)
        put :update, {:id => completed_exercise.to_param, :completed_exercise => { "exercise_id" => "invalid value" }}, valid_session
        assigns(:completed_exercise).should eq(completed_exercise)
      end

      it "re-renders the 'edit' template" do
        completed_exercise = CompletedExercise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedExercise.any_instance.stub(:save).and_return(false)
        put :update, {:id => completed_exercise.to_param, :completed_exercise => { "exercise_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested completed_exercise" do
      completed_exercise = CompletedExercise.create! valid_attributes
      expect {
        delete :destroy, {:id => completed_exercise.to_param}, valid_session
      }.to change(CompletedExercise, :count).by(-1)
    end

    it "redirects to the completed_exercises list" do
      completed_exercise = CompletedExercise.create! valid_attributes
      delete :destroy, {:id => completed_exercise.to_param}, valid_session
      response.should redirect_to(completed_exercises_url)
    end
  end

end
